import product1 from "../Image/Products/Stump Out.png";
import product2 from "../Image/Products/Jomraj.png";
import product3 from "../Image/Products/Black_Bold.png";
import product4 from "../Image/Products/Mohakal.png";
import product5 from "../Image/Products/Palowan.png";
import product6 from "../Image/Products/Agniastra.png";
import product7 from "../Image/Products/Ghayal.png";
import product8 from "../Image/Products/Hyena.png";
import product9 from "../Image/Products/Helmet-550.png";
import product10 from "../Image/Products/Iris_Super.png";
import product11 from "../Image/Products/Joonun.png";
import product12 from "../Image/Products/Mbappe-10.png";
import product13 from "../Image/Products/Foring.png";
import product14 from "../Image/Products/Trap.png";
import product15 from "../Image/Products/Ekta.png";
import product16 from "../Image/Products/Brahmashtra.png";
import product17 from "../Image/Products/T-20.png";
import product18 from "../Image/Products/Bhimrul.png";
import product19 from "../Image/Products/Relief.png";
import product20 from "../Image/Products/Manzeel.png";

import product21 from "../Image/Products/Panch Foren.png";
import product22 from "../Image/Products/Jonaki.png";
import product23 from "../Image/Products/Energy.png";
import product24 from "../Image/Products/Bruce_Lee.png";
import product25 from "../Image/Products/Bhromor.png";
import product26 from "../Image/Products/Aabha.png";
import product27 from "../Image/Products/Strawberry.png";
import product28 from "../Image/Products/Octopus.png";
import product29 from "../Image/Products/Energy Gold.png";

import product30 from "../Image/Products/Carbon_Plus.png";
import product31 from "../Image/Products/Energic Top.png";
import product32 from "../Image/Products/Arm Guard.png";
import product33 from "../Image/Products/Jhalak.png";

import product34 from "../Image/Products/Green_Plus.png";
import product35 from "../Image/Products/Barricade.png";
import product36 from "../Image/Products/Dugdugi.png";

import product37 from "../Image/Products/Zinger.png";
import product38 from "../Image/Products/Roop.png";
import product39 from "../Image/Products/Tandur.png";
import product40 from "../Image/Products/Ricardo.png";
import product41 from '../Image/Products/Gorilla-71.png';
import product42 from '../Image/Products/Corner.png';



export const allproducts = [
  {
    id: 1,
    product_name: "STUMP OUT",
    product_tag: "Emamectin Benzoate 1.9% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product1,
  },
  {
    id: 2,
    product_name: "JOMRAJ",
    product_tag: "Emamectin Benzoate 1.9% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product2,
  },
  {
    id: 3,
    product_name: "BLACK BOLD",
    product_tag: "Azadirachtin 0.03% (300 PPM) Min.",
    product_about: "",
    type: "Insecticide",
    product_img: product3,
  },
  {
    id: 4,
    product_name: "MOHAKAL",
    product_tag: "Emamectin Benzoate 5% SG",
    product_about: "",
    type: "Insecticide",
    product_img: product4,
  },
  {
    id: 5,
    product_name: "PALOWAN",
    product_tag: "Cypermethrin 10% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product5,
  },
  {
    id: 6,
    product_name: "AGNIASTRA",
    product_tag: "Cypermethrin 25% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product6,
  },
  {
    id: 7,
    product_name: "GHAYAL",
    product_tag: "Chlorpyriphos 20% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product7,
  },
  {
    id: 8,
    product_name: "HYENA",
    product_tag: "Monocrotophos 36% SL",
    product_about: "",
    type: "Insecticide",
    product_img: product8,
  },
  {
    id: 9,
    product_name: "HELMET -550",
    product_tag: "Chlorpyriphos 50%  + Cypermethrin 5% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product9,
  },
  {
    id: 10,
    product_name: "IRIS SUPER",
    product_tag: "Profenofos 40% + Cypermethrin 4% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product10,
  },
  {
    id: 11,
    product_name: "JOONUN",
    product_tag: "Pyriproxyfen 10% + Bifenthrin 10% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product11,
  },
  {
    id: 12,
    product_name: "MBAPPE-10",
    product_tag: "Imidacloprid 17.8% SL",
    product_about: "",
    type: "Insecticide",
    product_img: product12,
  },
  {
    id: 13,
    product_name: "FORING",
    product_tag: "Thiamethoxyfen 25% WG",
    product_about: "",
    type: "Insecticide",
    product_img: product13,
  },
  {
    id: 14,
    product_name: "TRAP",
    product_tag: "Accephate 75% SP",
    product_about: "",
    type: "Insecticide",
    product_img: product14,
  },
  {
    id: 15,
    product_name: "EKTA",
    product_tag: "Acetamiprid 20% SP",
    product_about: "",
    type: "Insecticide",
    product_img: product15,
  },
  {
    id: 16,
    product_name: "BRAHMASTRA",
    product_tag: "Cartap Hydrochloride 4% GR",
    product_about: "",
    type: "Insecticide",
    product_img: product16,
  },
  {
    id: 17,
    product_name: "T-20",
    product_tag: "Cartap Hydrochloride 50% SP",
    product_about: "",
    type: "Insecticide",
    product_img: product17,
  },
  {
    id: 18,
    product_name: "BHIMRUL",
    product_tag: "Fipronil 80% WG",
    product_about: "",
    type: "Insecticide",
    product_img: product18,
  },
  {
    id: 19,
    product_name: "RELIEF",
    product_tag: "Carbofuran 3% CG",
    product_about: "",
    type: "Insecticide",
    product_img: product19,
  },
  {
    id: 20,
    product_name: "MANZEEL",
    product_tag: "Organic Pest Controller",
    product_about: "",
    type: "Insecticide",
    product_img: product20,
  },
  {
    id: 21,
    product_name: "PANCH FORON",
    product_tag: "Plant Growth Regulators",
    product_about: "",
    type: "Fungicide",
    product_img: product21,
  },
  {
    id: 22,
    product_name: "JONAKI",
    product_tag: "Plant Bio Stimulant",
    product_about: "",
    type: "Fungicide",
    product_img: product22,
  },
  {
    id: 23,
    product_name: "ENERGY",
    product_tag: "Quinalphos 20%",
    type: "Fungicide",
    product_img: product23,
  },
  {
    id: 24,
    product_name: "BRUCE LEE",
    product_tag: "Ethaphone 39% SL",
    type: "Fungicide",
    product_img: product24,
  },
  {
    id: 25,
    product_name: "BHROMOR",
    product_tag: "High Performance Plant Entrieser",
    type: "Fungicide",
    product_img: product25,
  },
  {
    id: 26,
    product_name: "AABHA",
    product_tag: "Silicone Spreader",
    type: "Fungicide",
    product_img: product26,
  },
  {
    id: 27,
    product_name: "STRAWBERRY",
    product_tag: "Organic Micor Nutrient",
    type: "Fungicide",
    product_img: product27,
  },
  {
    id: 28,
    product_name: "OCTOPUS",
    product_tag: "Humic Acid 95%",
    type: "Fungicide",
    product_img: product28,
  },
  {
    id: 29,
    product_name: "ENERGY GOLD",
    product_tag: "Organic Micro Nutrient",
    type: "Fungicide",
    product_img: product29,
  },
  {
    id: 30,
    product_name: "CARBON +",
    product_tag: "Hexaconazole 5% SC",
    type: "Fungicide",
    product_img: product30,
  },
  {
    id: 31,
    product_name: "ENERGIC TOP",
    product_tag: "Azoxystrobin 18.2% + Difenoconazole 11.4%",
    type: "Fungicide",
    product_img: product31,
  },
  {
    id: 32,
    product_name: "ARM GUARD",
    product_tag: "Carbendazim 12% + Mancozeb 63% WP",
    type: "Fungicide",
    product_img: product32,
  },
  {
    id: 33,
    product_name: "JHALAK",
    product_tag: "Azoxystrobin 11.5% + Mancozeb 30% WP",
    type: "Fungicide",
    product_img: product33,
  },
  {
    id: 34,
    product_name: "GREEN +",
    product_tag: "Sulphur 80% WDG",
    product_about: "",
    type: "PGR",
    product_img: product34,
  },
  {
    id: 35,
    product_name: "BARRICADE",
    product_tag: "Carbedazim 50% WP",
    product_about: "",
    type: "PGR",
    product_img: product35,
  },
  {
    id: 36,
    product_name: "DUG DUGI",
    product_tag: "Mancozeb 50% WP",
    product_about: "",
    type: "PGR",
    product_img: product36,
  },
  {
    id: 37,
    product_name: "ZINGER",
    product_tag: "Pendamethalin 30% EC",
    product_about: "",
    type: "PGR",
    product_img: product37,
  },
  {
    id: 38,
    product_name: "ROOP",
    product_tag: "Glyphosate 41% SL",
    product_about: "",
    type: "PGR",
    product_img: product38,
  },
  {
    id: 39,
    product_name: "TANDUR",
    product_tag: "Paraquat Dichloride 24% SL",
    product_about: "",
    type: "PGR",
    product_img: product39,
  },
  {
    id: 40,
    product_name: "RICARDO",
    product_tag: "Pretilachlor 50% EC Ammounium Salt of",
    product_about: "",
    type: "PGR",
    product_img: product40,
  },
];

export const Insecticideproducts = [
  {
    id: 1,
    product_name: "STUMP OUT",
    product_tag: "Emamectin Benzoate 1.9% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product1,
  },
  {
    id: 2,
    product_name: "JOMRAJ",
    product_tag: "Emamectin Benzoate 1.9% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product2,
  },
  {
    id: 3,
    product_name: "BLACK BOLD",
    product_tag: "Azadirachtin 0.03% (300 PPM) Min.",
    product_about: "",
    type: "Insecticide",
    product_img: product3,
  },
  {
    id: 4,
    product_name: "MOHAKAL",
    product_tag: "Emamectin Benzoate 5% SG",
    product_about: "",
    type: "Insecticide",
    product_img: product4,
  },
  {
    id: 5,
    product_name: "PALOWAN",
    product_tag: "Cypermethrin 10% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product5,
  },
  {
    id: 6,
    product_name: "AGNIASTRA",
    product_tag: "Cypermethrin 25% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product6,
  },
  {
    id: 7,
    product_name: "GHAYAL",
    product_tag: "Chlorpyriphos 20% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product7,
  },
  {
    id: 8,
    product_name: "HYENA",
    product_tag: "Monocrotophos 36% SL",
    product_about: "",
    type: "Insecticide",
    product_img: product8,
  },
  {
    id: 9,
    product_name: "HELMET -550",
    product_tag: "Chlorpyriphos 50%  + Cypermethrin 5% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product9,
  },
  {
    id: 10,
    product_name: "IRIS SUPER",
    product_tag: "Profenofos 40% + Cypermethrin 4% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product10,
  },
  {
    id: 11,
    product_name: "JOONUN",
    product_tag: "Pyriproxyfen 10% + Bifenthrin 10% EC",
    product_about: "",
    type: "Insecticide",
    product_img: product11,
  },
  {
    id: 12,
    product_name: "MBAPPE-10",
    product_tag: "Imidacloprid 17.8% SL",
    product_about: "",
    type: "Insecticide",
    product_img: product12,
  },
  {
    id: 13,
    product_name: "FORING",
    product_tag: "Thiamethoxyfen 25% WG",
    product_about: "",
    type: "Insecticide",
    product_img: product13,
  },
  {
    id: 14,
    product_name: "TRAP",
    product_tag: "Accephate 75% SP",
    product_about: "",
    type: "Insecticide",
    product_img: product14,
  },
  {
    id: 15,
    product_name: "EKTA",
    product_tag: "Acetamiprid 20% SP",
    product_about: "",
    type: "Insecticide",
    product_img: product15,
  },
  {
    id: 16,
    product_name: "BRAHMASTRA",
    product_tag: "Cartap Hydrochloride 4% GR",
    product_about: "",
    type: "Insecticide",
    product_img: product16,
  },
  {
    id: 17,
    product_name: "T-20",
    product_tag: "Cartap Hydrochloride 50% SP",
    product_about: "",
    type: "Insecticide",
    product_img: product17,
  },
  {
    id: 18,
    product_name: "BHIMRUL",
    product_tag: "Fipronil 80% WG",
    product_about: "",
    type: "Insecticide",
    product_img: product18,
  },
  {
    id: 19,
    product_name: "RELIEF",
    product_tag: "Carbofuran 3% CG",
    product_about: "",
    type: "Insecticide",
    product_img: product19,
  },
  {
    id: 20,
    product_name: "MANZEEL",
    product_tag: "Organic Pest Controller",
    product_about: "",
    type: "Insecticide",
    product_img: product20,
  },
];

export const Fungicideproducts = [
  {
    id: 25,
    product_name: "BHROMOR",
    product_tag: "High Performance Plant Entrieser",
    product_about: "",
    type: "Fungicide",
    product_img: product25,
  },
  {
    id: 26,
    product_name: "AABHA",
    product_tag: "Silicone Spreader",
    product_about: "",
    type: "Fungicide",
    product_img: product26,
  },
  {
    id: 27,
    product_name: "STRAWBERRY",
    product_tag: "Organic Micor Nutrient",
    product_about: "",
    type: "Fungicide",
    product_img: product27,
  },
  {
    id: 28,
    product_name: "OCTOPUS",
    product_tag: "Humic Acid 95%",
    product_about: "",
    type: "Fungicide",
    product_img: product28,
  },
  {
    id: 29,
    product_name: "ENERGY GOLD",
    product_tag: "Organic Micro Nutrient",
    product_about: "",
    type: "Fungicide",
    product_img: product29,
  },
  {
    id: 30,
    product_name: "CARBON +",
    product_tag: "Hexaconazole 5% SC",
    product_about: "",
    type: "Fungicide",
    product_img: product30,
  },
  {
    id: 31,
    product_name: "ENERGIC TOP",
    product_tag: "Azoxystrobin 18.2% + Difenoconazole 11.4%",
    product_about: "",
    type: "Fungicide",
    product_img: product31,
  },
  {
    id: 32,
    product_name: "ARM GUARD",
    product_tag: "Carbendazim 12% + Mancozeb 63% WP",
    product_about: "",
    type: "Fungicide",
    product_img: product32,
  },
  {
    id: 33,
    product_name: "JHALAK",
    product_tag: "Azoxystrobin 11.5% + Mancozeb 30% WP",
    product_about: "",
    type: "Fungicide",
    product_img: product33,
  },
  {
    id: 34,
    product_name: "GREEN +",
    product_tag: "Sulphur 80% WDG",
    product_about: "",
    type: "Fungicide",
    product_img: product34,
  },
  {
    id: 35,
    product_name: "BARRICADE",
    product_tag: "Carbedazim 50% WP",
    product_about: "",
    type: "Fungicide",
    product_img: product35,
  },
  {
    id: 36,
    product_name: "DUG DUGI",
    product_tag: "Mancozeb 50% WP",
    product_about: "",
    type: "Fungicide",
    product_img: product36,
  },
  {
    id: 37,
    product_name: "ZINGER",
    product_tag: "Pendamethalin 30% EC",
    product_about: "",
    type: "Fungicide",
    product_img: product37,
  },
  {
    id: 38,
    product_name: "ROOP",
    product_tag: "Glyphosate 41% SL",
    product_about: "",
    type: "Fungicide",
    product_img: product38,
  },
  {
    id: 39,
    product_name: "TANDUR",
    product_tag: "Paraquat Dichloride 24% SL",
    product_about: "",
    type: "Fungicide",
    product_img: product39,
  },
  {
    id: 40,
    product_name: "RICARDO",
    product_tag: "Pretilachlor 50% EC Ammounium Salt of",
    product_about: "",
    type: "Fungicide",
    product_img: product40,
  },
];

export const Herbicideproducts = [
  {
    id: 1,
    product_name: "STUMP OUT",
    product_tag: "Emamectin Benzoate 1.9% EC",
    product_about: "",
    type: "Herbicide",
    product_img: product1,
  },
  {
    id: 6,
    product_name: "AGNIASTRA",
    product_tag: "Cypermethrin 25% EC",
    product_about: "",
    type: "Herbicide",
    product_img: product6,
  },
  {
    id: 7,
    product_name: "GHAYAL",
    product_tag: "Chlorpyriphos 20% EC",
    product_about: "",
    type: "Herbicide",
    product_img: product7,
  },
  {
    id: 8,
    product_name: "HYENA",
    product_tag: "Monocrotophos 36% SL",
    product_about: "",
    type: "Herbicide",
    product_img: product8,
  },
  {
    id: 9,
    product_name: "HELMET -550",
    product_tag: "Chlorpyriphos 50%  + Cypermethrin 5% EC",
    product_about: "",
    type: "Herbicide",
    product_img: product9,
  },
  {
    id: 10,
    product_name: "IRIS SUPER",
    product_tag: "Profenofos 40% + Cypermethrin 4% EC",
    product_about: "",
    type: "Herbicide",
    product_img: product10,
  },
  {
    id: 15,
    product_name: "EKTA",
    product_tag: "Acetamiprid 20% SP",
    product_about: "",
    type: "Herbicide",
    product_img: product15,
  },
  {
    id: 16,
    product_name: "BRAHMASTRA",
    product_tag: "Cartap Hydrochloride 4% GR",
    product_about: "",
    type: "Herbicide",
    product_img: product16,
  },
  {
    id: 20,
    product_name: "MANZEEL",
    product_tag: "Organic Pest Controller",
    product_about: "",
    type: "Herbicide",
    product_img: product20,
  },
  {
    id: 21,
    product_name: "PANCH FORON",
    product_tag: "Plant Growth Regulators",
    product_about: "",
    type: "Herbicide",
    product_img: product21,
  },
  {
    id: 22,
    product_name: "JONAKI",
    product_tag: "Plant Bio Stimulant",
    product_about: "",
    type: "Herbicide",
    product_img: product22,
  },
  {
    id: 23,
    product_name: "ENERGY",
    product_tag: "Quinalphos 20%",
    product_about: "",
    type: "Herbicide",
    product_img: product23,
  },
  {
    id: 24,
    product_name: "BRUCE LEE",
    product_tag: "Ethaphone 39% SL",
    product_about: "",
    type: "Herbicide",
    product_img: product24,
  },
  {
    id: 28,
    product_name: "OCTOPUS",
    product_tag: "Humic Acid 95%",
    product_about: "",
    type: "Herbicide",
    product_img: product28,
  },
  {
    id: 29,
    product_name: "ENERGY GOLD",
    product_tag: "Organic Micro Nutrient",
    product_about: "",
    type: "Herbicide",
    product_img: product29,
  },
  {
    id: 30,
    product_name: "CARBON +",
    product_tag: "Hexaconazole 5% SC",
    product_about: "",
    type: "Herbicide",
    product_img: product30,
  },
  {
    id: 34,
    product_name: "GREEN +",
    product_tag: "Sulphur 80% WDG",
    product_about: "",
    type: "Herbicide",
    product_img: product34,
  },
  {
    id: 35,
    product_name: "BARRICADE",
    product_tag: "Carbedazim 50% WP",
    product_about: "",
    type: "Herbicide",
    product_img: product35,
  },
  {
    id: 36,
    product_name: "DUG DUGI",
    product_tag: "Mancozeb 50% WP",
    product_about: "",
    type: "Herbicide",
    product_img: product36,
  },
  {
    id: 37,
    product_name: "ZINGER",
    product_tag: "Pendamethalin 30% EC",
    product_about: "",
    type: "Herbicide",
    product_img: product37,
  },
];

export const PGRproducts = [
  {
    id: 6,
    product_name: "AGNIASTRA",
    product_tag: "Cypermethrin 25% EC",
    product_about: "",
    type: "PGR",
    product_img: product6,
  },
  {
    id: 10,
    product_name: "IRIS SUPER",
    product_tag: "Profenofos 40% + Cypermethrin 4% EC",
    product_about: "",
    type: "PGR",
    product_img: product10,
  },
  {
    id: 15,
    product_name: "EKTA",
    product_tag: "Acetamiprid 20% SP",
    product_about: "",
    type: "PGR",
    product_img: product15,
  },
  {
    id: 21,
    product_name: "PANCH FORON",
    product_tag: "Plant Growth Regulators",
    product_about: "",
    type: "PGR",
    product_img: product21,
  },
  {
    id: 22,
    product_name: "JONAKI",
    product_tag: "Plant Bio Stimulant",
    product_about: "",
    type: "PGR",
    product_img: product22,
  },
  {
    id: 28,
    product_name: "OCTOPUS",
    product_tag: "Humic Acid 95%",
    product_about: "",
    type: "PGR",
    product_img: product28,
  },
  {
    id: 29,
    product_name: "ENERGY GOLD",
    product_tag: "Organic Micro Nutrient",
    product_about: "",
    type: "PGR",
    product_img: product29,
  },
  {
    id: 30,
    product_name: "CARBON +",
    product_tag: "Hexaconazole 5% SC",
    product_about: "",
    type: "PGR",
    product_img: product30,
  },
  {
    id: 37,
    product_name: "ZINGER",
    product_tag: "Pendamethalin 30% EC",
    product_about: "",
    type: "PGR",
    product_img: product37,
  },
];


export const Insecticidesimilarpoduct = [
  {
    id: 6,
    product_name: "AGNIASTRA",
    product_tag: "Cypermethrin 25% EC",
    product_about: "",
    product_img: product6,
  },
  {
    id: 10,
    product_name: "IRIS SUPER",
    product_tag: "Profenofos 40% + Cypermethrin 4% EC",
    product_about: "",
    product_img: product10,
  },
  {
    id: 15,
    product_name: "EKTA",
    product_tag: "Acetamiprid 20% SP",
    product_about: "",
    product_img: product15,
  },
  {
    id: 21,
    product_name: "PANCH FORON",
    product_tag: "Plant Growth Regulators",
    product_about: "",
    product_img: product21,
  },
];


export const Fungicidesimilarpoduct = [
  {
    id: 6,
    product_name: "AGNIASTRA",
    product_tag: "Cypermethrin 25% EC",
    product_about: "",
    product_img: product6,
  },
  {
    id: 10,
    product_name: "IRIS SUPER",
    product_tag: "Profenofos 40% + Cypermethrin 4% EC",
    product_about: "",
    product_img: product10,
  },
  {
    id: 15,
    product_name: "EKTA",
    product_tag: "Acetamiprid 20% SP",
    product_about: "",
    product_img: product15,
  },
  {
    id: 21,
    product_name: "PANCH FORON",
    product_tag: "Plant Growth Regulators",
    product_about: "",
    product_img: product21,
  },
];

export const Herbicidesimilarpoduct = [
  {
    id: 6,
    product_name: "AGNIASTRA",
    product_tag: "Cypermethrin 25% EC",
    product_about: "",
    product_img: product6,
  },
  {
    id: 10,
    product_name: "IRIS SUPER",
    product_tag: "Profenofos 40% + Cypermethrin 4% EC",
    product_about: "",
    product_img: product10,
  },
  {
    id: 15,
    product_name: "EKTA",
    product_tag: "Acetamiprid 20% SP",
    product_about: "",
    product_img: product15,
  },
  {
    id: 21,
    product_name: "PANCH FORON",
    product_tag: "Plant Growth Regulators",
    product_about: "",
    product_img: product21,
  },
];

export const PGRsimilarpoduct = [
  {
    id: 6,
    product_name: "AGNIASTRA",
    product_tag: "Cypermethrin 25% EC",
    product_about: "",
    product_img: product6,
  },
  {
    id: 10,
    product_name: "IRIS SUPER",
    product_tag: "Profenofos 40% + Cypermethrin 4% EC",
    product_about: "",
    product_img: product10,
  },
  {
    id: 15,
    product_name: "EKTA",
    product_tag: "Acetamiprid 20% SP",
    product_about: "",
    product_img: product15,
  },
  {
    id: 21,
    product_name: "PANCH FORON",
    product_tag: "Plant Growth Regulators",
    product_about: "",
    product_img: product21,
  },
];